### ISSUE TITLE
MLS Awaiting Customer Photos Workflow is broken

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#294]
MLS Awaiting Customer Photos Workflow is broken - when you put an order in this status, it does not appear in the workflow for MLS.
Submitted By: Nicole

**Comment by Juvie92** [comment]
I believe I found the fix for this. In the database under the "workflow_step" table, in the "Awaiting Customer Photos", "is_problem" needs to be changed from 0 to 1. I think I found where it only selects those in the "WorkflowDashboardBlockController" but if we get a chance can we go over this just to be sure.

**Comment by sean8300** [comment]
It looks like awaiting customer photos is a problem, regular awaiting photos isnt.  asked Nicole for clarity

**Comment by sean8300** [comment]
Spoke with Nicole, this was fixed a long time ago
