### ISSUE TITLE
Discount Code Reflection

### ISSUE THREAD

**Issue by sean8300** [sean8300/listerassister_issues#623]
Noticed on this order the Discount code is not showing the code entered but the order total does reflect the correct price with discount. Not sure if this is only affecting new orders or all orders   #180327 
 Submitted By:  Meghan Levy

**Comment by Juvie92** [comment]
This may be a rare bug that we need to keep track of just to know how often it comes up. 

Took a look and after trying to replicate this, noticed that the discount code does show up on the suborder. Double checked the database to see if a coupon_code had been set in the listing table and it had for both suborder and original listings. I then refreshed the original order and the discount code appeared. 

Wasn't able to get it to appear on live but seems the code is there due to it showing up on the suborder.
